services:
  backend:
    build: ./backend
    image: routparesh/task-tracker-backend-app:v1
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mongo-service
  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL=http://api.paresh.work
    image: routparesh/task-tracker-frontend-app:v1
    ports:
      - '80:80'
    depends_on:
      - backend
  mongo-service:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - 'mongo_data:/data/db/'
volumes:
  mongo_data:
