apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-app-backend
  labels:
    app: task-tracker-app-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-tracker-app-backend
  template:
    metadata:
      labels:
        app: task-tracker-app-backend
    spec:
      containers:
        - name: task-tracker-app-backend
          image: routparesh/task-tracker-backend-app:123835b246c518ec1f1e1ebb489d7003a8e5d595
          ports:
            - containerPort: 3000
