apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-app-backend
  labels:
    app: task-tracker-app-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-tracker-app-backend
  template:
    metadata:
      labels:
        app: task-tracker-app-backend
    spec:
      containers:
        - name: task-tracker-app-backend
          image: routparesh/task-tracker-backend-app:2f40bc14faac03efa11de3705a21dfa6749da86d
          ports:
            - containerPort: 3000
