apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-app-backend
  labels:
    app: task-tracker-app-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-tracker-app-backend
  template:
    metadata:
      labels:
        app: task-tracker-app-backend
    spec:
      containers:
        - name: task-tracker-app-backend
          image: routparesh/task-tracker-backend-app:a052aab8b59d1bcfb85e3f2d4d6e3979a34a3512
          ports:
            - containerPort: 3000
