apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-app-backend
  labels:
    app: task-tracker-app-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-tracker-app-backend
  template:
    metadata:
      labels:
        app: task-tracker-app-backend
    spec:
      containers:
        - name: task-tracker-app-backend
          image: routparesh/task-tracker-backend-app:50af17335d9346e5d48440bf128552ff7b880d29
          ports:
            - containerPort: 3000
