apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-app-backend
  labels:
    app: task-tracker-app-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-tracker-app-backend
  template:
    metadata:
      labels:
        app: task-tracker-app-backend
    spec:
      containers:
        - name: task-tracker-app-backend
          image: routparesh/task-tracker-backend-app:6521b55d8f40f39af04b87a991adda411c8e11de
          ports:
            - containerPort: 3000
