apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-app
  labels:
    app: task-tracker-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-tracker-app
  template:
    metadata:
      labels:
        app: task-tracker-app
    spec:
      containers:
        - name: task-tracker-app-frontend
          image: routparesh/task-tracker-frontend-app:f65326988d51a0542878e37f9f671188bf3b45a8
          ports:
            - containerPort: 80
