apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-app
  labels:
    app: task-tracker-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-tracker-app
  template:
    metadata:
      labels:
        app: task-tracker-app
    spec:
      containers:
        - name: task-tracker-app-frontend
          image: routparesh/task-tracker-frontend-app:3ee8a866c157ad9cc506551e6d5837a36222f142
          ports:
            - containerPort: 80
