apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-app
  labels:
    app: task-tracker-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-tracker-app
  template:
    metadata:
      labels:
        app: task-tracker-app
    spec:
      containers:
        - name: task-tracker-app-frontend
          image: routparesh/task-tracker-frontend-app:ce3b3315918f144b964c61e158bd43393fc75e7f
          ports:
            - containerPort: 80
