apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-app
  labels:
    app: task-tracker-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-tracker-app
  template:
    metadata:
      labels:
        app: task-tracker-app
    spec:
      containers:
        - name: task-tracker-app-frontend
          image: routparesh/task-tracker-frontend-app:50af17335d9346e5d48440bf128552ff7b880d29
          ports:
            - containerPort: 80
