apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-app
  labels:
    app: task-tracker-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-tracker-app
  template:
    metadata:
      labels:
        app: task-tracker-app
    spec:
      containers:
        - name: task-tracker-app-frontend
          image: routparesh/task-tracker-frontend-app:e7ddf40b7dcb17573d8608bbd5022e713f32cffb
          ports:
            - containerPort: 80
