apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-target-type: ip
spec:
  type: ClusterIP
  selector:
    app: task-tracker-app # Ensure this matches Deployment
  ports:
    - port: 80
      targetPort: 80
